<?php

use Illuminate\Database\Seeder;

class ImageContentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('image_contents')->insert(['id' => '1','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'popup','path' => 'photos/cms/popup/E9x9HsWzpHx5wb9LD8VXLz04zjHSPfzKlau1bRWa.jpeg','alt' => 'simpledasdasd','order' => NULL,'enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '41','deleted_by' => NULL,'created_at' => '2021-06-10 00:08:05','updated_at' => '2021-08-14 03:42:53','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '2','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'mobile','path' => 'photos/cms/mobile/i8BSUxDrlnIjYggCzRzeEwHJZq6WsI5hR0cQaxJs.gif','alt' => 'test banner mobile','order' => NULL,'enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '84','deleted_by' => NULL,'created_at' => '2021-06-10 00:08:32','updated_at' => '2021-08-25 06:41:31','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '3','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/NuWRFnq2ira5IOe0uwcCCFKxANMEyMzsZyGjR4xk.jpeg','alt' => 'slide 2','order' => '3','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-06-10 00:09:01','updated_at' => '2021-08-25 07:03:14','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '4','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/imceCSXZxyIoKMH021uu8TkmgGedMWBVXLFdPAUR.jpeg','alt' => 'slide 1','order' => '6','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '1','deleted_by' => '1','created_at' => '2021-06-10 00:09:35','updated_at' => '2021-08-25 05:40:00','deleted_at' => '2021-08-25 05:40:00']);

        \DB::table('image_contents')->insert(['id' => '5','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/VspaBRKeBL8jMxRaEqGIvvGkj8xaPukMMymPwyU9.jpg','alt' => 'slide 3dasdas','order' => '2','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '1','deleted_by' => '1','created_at' => '2021-06-10 00:11:11','updated_at' => '2021-08-25 05:40:09','deleted_at' => '2021-08-25 05:40:09']);

        \DB::table('image_contents')->insert(['id' => '8','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/gjOyA2pNjDImYd59k5PIClXVTRws29V2ERPwLGh3.jpg','alt' => 'slide 4','order' => '2','enabled' => '0','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '41','deleted_by' => '1','created_at' => '2021-06-15 00:00:19','updated_at' => '2021-08-25 05:40:10','deleted_at' => '2021-08-25 05:40:10']);

        \DB::table('image_contents')->insert(['id' => '9','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/fp8e67Gha5HnVHlSRuGUQFJYnfebb0Ni4Z1Wg4km.jpg','alt' => 'slide 5','order' => '4','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '1','deleted_by' => '1','created_at' => '2021-06-15 00:00:45','updated_at' => '2021-08-25 05:40:06','deleted_at' => '2021-08-25 05:40:06']);

        \DB::table('image_contents')->insert(['id' => '10','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/BIxMk9622BHny2q7OdcFBU0HbhFtp0zvMLYjI4BN.jpg','alt' => 'slide 6','order' => '2','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '35','updated_by' => '1','deleted_by' => '1','created_at' => '2021-06-15 00:01:00','updated_at' => '2021-08-25 05:40:36','deleted_at' => '2021-08-25 05:40:36']);

        \DB::table('image_contents')->insert(['id' => '11','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/JqgJhio3h4duCwCXMisWnnxolMwDXpJ3GsiLFKVr.jpg','alt' => 'This is for Desktop NUMBER ONE (approved by Rey)','order' => '7','enabled' => '0','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => '1','created_at' => '2021-08-10 08:58:54','updated_at' => '2021-08-25 05:39:55','deleted_at' => '2021-08-25 05:39:55']);

        \DB::table('image_contents')->insert(['id' => '12','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/1XcnE3NYeJVTFSBtH0yRjfxVhbqnTn4OjuMbfboR.jpg','alt' => 'This is for Desktop NUMBER TWO (approved by Rey)','order' => '8','enabled' => '0','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '1','updated_by' => '1','deleted_by' => '1','created_at' => '2021-08-10 09:23:10','updated_at' => '2021-08-25 05:40:33','deleted_at' => '2021-08-25 05:40:33']);

        \DB::table('image_contents')->insert(['id' => '13','constant_promosi_value_id' => NULL,'title' => 'EVENT TURNOVER UNTUK SEMUA PERMAINAN CIKASLOT HADIAH MILIARAN','type' => 'turnover','path' => 'photos/cms/promotion/hzMEXF6ZaXe4FhVoMDfx0palynzUfpkRtehREPHy.png','alt' => 'turnover','order' => '3','enabled' => '1','content' => '<div>&nbsp;</div><div>- Pencapaian Turnover(50) Juta = Saldo Sebesar Rp 50.000</div><div>- Pencapaian Turnover(100) Juta = Saldo Sebesar Rp 100.000</div><div>- Pencapaian Turnover(200) Juta = Saldo Sebesar Rp 200.000</div><div>- Pencapaian Turnover(300) Juta = Saldo Sebesar Rp 300.000</div><div>- Pencapaian Turnover(500) Juta = Saldo Sebesar Rp 600.000</div><div>- Pencapaian TurnOver(1)Milliar = Saldo Sebesar Rp 1.500.000</div><div>- Pencapaian TurnOver(2)Milliar = Saldo Sebesar Rp 3.000.000</div><div>- Pencapaian TurnOver(5)Milliar = Hp Samsung S21+ Ultra 128gb</div><div>- Pencapaian TurnOver(10)Milliar = Hp Iphone 12 Pro Max 256GB</div><div>- Pencapaian TurnOver(25)Milliar = Yamaha XMAX 250</div><div>- Pencapaian TurnOver(50)Milliar = Kawasaki Z126 PRO 2021</div><div>- Pencapaian TurnOver(100)Milliar = Honda Accord 2021</div><div>- Pencapaian TurnOver(1)TRILIUN = Mercedes Benz GL-400<br><br><br><strong>Syarat dan Ketentuan :</strong><br><br></div><div>Promo dibatalkan jika terdapat kesamaan Data Rekening, IP Address, Email, dan No.Handphone. No risk bet, up normal, Bet Kanan/Kiri kecurangan lainnya.</div><div>Jika terindikasi segala bentuk kecurangan atau memanipulasi bonus, maka pihak CIKA4D berhak membatalkan bonus serta suspend user id tersebut secara permanen.&nbsp;</div>','max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '40','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-14 08:01:55','updated_at' => '2021-09-17 22:18:26','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '14','constant_promosi_value_id' => '1','title' => 'BONUS NEW MEMBER 20%','type' => 'bonus','path' => 'photos/cms/promotion/Rh6P9Y08UdQEg2UGCgIZr5EyCdpxv6mMjoFdkSIf.jpg','alt' => 'bonus new member','order' => '1','enabled' => '0','content' => '<div>BONUS NEW MEMBER 20%&nbsp;&nbsp;</div>','max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '40','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-14 09:09:28','updated_at' => '2021-08-14 09:10:14','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '15','constant_promosi_value_id' => '1','title' => 'cashback','type' => 'cashback','path' => 'photos/cms/promotion/wZjBeBChdIjVfKkWX0wr12rqtukpjNuUqTbgnSqb.png','alt' => 'cashback','order' => '3','enabled' => '1','content' => '<div>content</div>','max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '40','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-15 12:04:58','updated_at' => '2021-09-17 22:19:03','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '16','constant_promosi_value_id' => '2','title' => 'BONUS NEW MEMBER 20%','type' => 'bonus_new_member','path' => 'photos/cms/promotion/KRqMEoG8nYcf2Iq9zqWRyP6ecMBMMF4tUrL6HaEz.png','alt' => 'bonus','order' => '3','enabled' => '1','content' => '<div>&nbsp;</div><div><strong>Syarat Dan ketentuan :<br></strong><br></div><div><br></div><div>- Min Deposit IDR 50.000,-</div><div>- Maximal bonus diberikan IDR 20.000,-</div><div>- Syarat Turn Over 3x (Contoh : DP 50.000 + 20% = 60.000 x 3 = 180.000 TO yang harus anda capai untuk melakukan withdraw)</div><div>- Tidak menerima invest dalam bonus berikut</div><div>- Bonus Member Baru 20% ini tidak berlaku untuk permainan Togel</div><div>- Bonus Member Baru klaim di awal deposit&nbsp;</div>','max_bonus_given' => '20000','value_bonus' => '20','created_by' => '40','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-16 01:47:47','updated_at' => '2021-09-17 22:18:43','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '17','constant_promosi_value_id' => '1','title' => 'BONUS NEXT DEPOSIT 10%','type' => 'bonus_next_deposit','path' => 'photos/cms/promotion/QKJsyEkSAmlsw2tCG6lEC6w9VNZlgzSkJ5yAzjS4.png','alt' => 'next depo','order' => '2','enabled' => '1','content' => '<div>&nbsp;</div><div><strong>Syarat Dan ketentuan :<br></strong><br></div><div><br></div><div>- Min Deposit IDR 50.000,-</div><div>- Maksimal bonus diberikan IDR 10.000,-</div><div>- Member berhak klaim 1 x dalam 1 hari.</div><div>- Syarat Turn Over 3x (Contoh : DP 50.000 + 10% = 55000 x 3 = 165.000 TO yang harus anda capai untuk melakukan withdraw)</div><div>- Tidak menerima invest dalam bonus berikut.</div><div>- Bonus ini tidak berlaku untuk permainan Togel</div><div>- Bonus Deposit Harian klaim di awal deposit&nbsp;</div>','max_bonus_given' => '10000','value_bonus' => '10','created_by' => '40','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-18 03:29:36','updated_at' => '2021-09-17 22:18:52','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '18','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/XTlAsVhpg8BZnqiXyRrpkIdjCLfoThSzdZULc3lf.jpeg','alt' => NULL,'order' => '4','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '1','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-25 05:44:05','updated_at' => '2021-08-25 07:03:16','deleted_at' => NULL]);

        \DB::table('image_contents')->insert(['id' => '19','constant_promosi_value_id' => NULL,'title' => NULL,'type' => 'slide','path' => 'photos/cms/slide/CsMSl1rY0F0OeHwMsTtiq4wuuPMNTVdPzqYU8M8M.jpeg','alt' => NULL,'order' => '5','enabled' => '1','content' => NULL,'max_bonus_given' => NULL,'value_bonus' => NULL,'created_by' => '1','updated_by' => '40','deleted_by' => NULL,'created_at' => '2021-08-25 05:44:13','updated_at' => '2021-08-25 07:03:18','deleted_at' => NULL]);


    }
}
