name: Deploy To Productions 

on:
  push:
    branches:
      - master 

  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master 
      - name: Deploy Agent Rest API 
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.IP_AGENT_REST_STAGING }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.KEY}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
        
  slackNotification:
    needs: deploy
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: "Cikatech 🚀🚀"
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_LINK_NAMES: true
        SLACK_MESSAGE: 'Success Deploy Productions :rocket: Agent deployed @backdev-team @frontdev-team '
        SLACK_TITLE:   ${{ github.event.head_commit.message }}
        SLACK_WEBHOOK: ${{ secrets.CIKATECH_SLACK_HOOK}}
        SLACK_FOOTER: "Efforts don't betray the results"
