name: Deploy Agent Rest API Staging 

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master 
      - name: Deploy Agent Rest API To Staging 
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.IP_AGENT_REST_STAGING }}
          username: ${{ secrets.HOSTNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            whoami
            ls -la
            ./rest.sh
        
  slackNotification:
    needs: deploy
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_FOOTER: "Efforts don't betray the results"
        SLACK_USERNAME: "CikaTech"
        SLACK_ICON_EMOJI: ':cuddle:'
        SLACK_LINK_NAMES: true
        SLACK_MESSAGE: ':gas: Agent Rest API Staging deployed successfully @backdev-team'
        SLACK_TITLE:   ${{ github.event.head_commit.message }}
        SLACK_WEBHOOK: ${{ secrets.SLACK}}
